import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col h-screen justify-center">
        {/* Navbar */}
        <Navbar />

        {/* Main Content */}
        <div className={`${inter.className} flex-grow py-16 px-10`}>
          {children}
        </div>

        {/* Footer */}
        <footer className=" bg-gray-300 text-white text-center py-4 w-full">
          <p>&copy; 2024 RianSoft 리안소프트. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
